project:
  type: book
  output-dir: docs

book:
  title: "Boletin estadístico Sede Palmira"
  author: "Jimena Lopez"
  date: "25/11/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - presentacion.qmd
    - Aspirantes.qmd
    - PruebasSaber.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual
delete_merged_file: true

