project:
  type: book
  output-dir: docs

book:
  title: "Boletin Sede Palmira"
  author: "Jimena Lopez"
  date: "25/11/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - Aspirantes.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

