# Presentación {.unnumbered}

La Universidad Nacional de Colombia en su Plan Global de Desarrollo 2013-2015 “Calidad Académica y Autonomía Responsable” propuso como una de las metas en el Programa Gestión de Calidad y desarrollo organizacional, “Constituir la Unidad Estadística Nacional adscrita a la Oficina Nacional de Planeación”, con el propósito de
definir, implementar y evaluar las políticas y el fomento de las buenas prácticas estadísticas que permitan disponer de información estratégica institucional con altos estándares de calidad.

Mediante el Acuerdo 113 de 2013 del CSU fue creada la que actualmente es la Dirección Nacional de Planeación y Estadística, pues disponer de información pertinente, oportuna, válida y confiable, representa un gran papel para la toma de decisiones y la implementación de políticas institucionales en la búsqueda de un mejoramiento continuo en nuestro quehacer institucional.

Es así como la Sede Palmira entrega a la comunidad universitaria y a la sociedad el séptimo Boletín Estadístico de la Sede Palmira que inició en el año 2009 y que busca recopilar las cifras más importantes de la Sede durante el último período, con una evolución de los últimos años que dan cuenta de la gestión académica realizada y aporta información pertinente al interior de la Sede para procesos de autoevaluación y mejoramiento continuo de nuestros programas curriculares y actividades misionales.

Este séptimo Boletín de Sede presenta los indicadores básicos de la Sede del último periodo registrado, y su evolución histórica, información detallada de [aspirantes y admitidos](Aspirantes.qmd) y [estudiante](PoblacionEstudiantil.qmd), [docencia](Doc), [administrativos](Admini),..., que de acuerdo al interés particular de cada lector podrá conocer en detalle y dar el uso e interpretación que considere.

El Boletín Estadístico de la Sede presenta información complementaria a las cifras e indicadores que presenta la Oficina Nacional de Planeación anualmente en la Revista de Estadísticas e Indicadores de la Universidad Nacional, detallando o ampliando información de formación, estudiantes, bienestar e investigación propias de la Sede, que sirvan a los diferentes actores a proponer ideas para su desarrollo. Se entrega este Boletín para ser consultado por los integrantes de la comunidad universitaria para su conocimiento y aplicación en sus proyecciones o procesos de acreditación de programas en la Sede Palmira.


```{r}
#| echo: false
#| message: false
#| warning: false
#| eval: false

# Propuesta paleta de colores

color <- function(n_colores){
  salida <- colorRampPalette(c("#6495ED", "#8cc63f", "#FFD700", "#f15a24", "#DA70D6"))(n_colores)
  return(salida)
}

boxplot(matrix(rnorm(2500), ncol = 12), 
        col = color(12), axes = FALSE)
```

